services:
  notion_backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: npm run start:dev
    env_file: 
      - ./.env
    ports: 
      - '5000:5000'
    volumes:
      - .:/app
